### ISSUE TITLE
Num dá num funciona

### ISSUE THREAD

**Issue by naps62** [andrefs/sb-projects-beatriz#1]
além de tar todo lixado a nivel de layout (parece que tá sempre me modo mobile), os sons em si num dão nem funcionam

**Comment by andrefs** [comment]
Em que browser, com que tamanho de ecrã, screenshots?

**Comment by naps62** [comment]
Google Chrome 44.0.2403.130 (64-bit)
Arch Linux  4.1.6-1-ARCH
1920x1080, não-retina

![screenshot from 2015-09-28 23-33-25](https://cloud.githubusercontent.com/assets/283819/10150761/5b085994-6639-11e5-8eaa-d23770f93a9c.png)

a mesma coisa acontece nos outros 2 sites

**Comment by andrefs** [comment]
http://stackoverflow.com/questions/23341765/getting-neterr-blocked-by-client-error-on-some-ajax-calls

**Comment by naps62** [comment]
olha, vai-se a ver e é o Privacy Badger. Esse cdn.ink.sapo.pt anda a tentar espiar-me?

**Comment by andrefs** [comment]
Já não és a primeira pessoa a reportar problemas entre a cdn do sapo e o
Privacy Badger.

Pá, acho que o PB só bloqueia por serem pedidos a um domínio diferente, e a
CDN do sapo não deve estar na whitelist deles -_-

Anyway, tnks pelo report ;)
